=== CodeAngie/BryansCafe/xml/menu.dtd
<!ELEMENT menu (meals, beverages, otherBeverages)>
<!ELEMENT meals (meal+)>
<!ELEMENT meal (name, image, price, description)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>

<!ELEMENT beverages (beverage+)>
<!ELEMENT beverage (name, image, sizes, description)>
<!ELEMENT sizes (size+)>
<!ELEMENT size (name, price)>

<!ELEMENT otherBeverages (beverage+)>

=== CodeAngie/BryansCafe/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "./menu.dtd">
<menu>
    <meals>
        <meal>
            <name>Beetroot and feta salad</name>
            <image>./assets/images/beetroot.jpg</image>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
        </meal>
        <meal>
            <name>Sourdough Rye Sandwich</name>
            <image>./assets/images/sandwich.jpg</image>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
        </meal>
        <meal>
            <name>Spinach Pie and Salad</name>
            <image>./assets/images/spinach.jpg</image>
            <price>$20.00</price>
            <description>Tasty pie with salad</description>
        </meal>
        <meal>
            <name>Feta pancakes with salad</name>
            <image>./assets/images/pancakes.jpg</image>
            <price>$19.50</price>
            <description>Tasty pancake filled with feta and salad</description>
        </meal>
    </meals>
    <beverages>
        <beverage>
            <name>Coffee and hot chocolates</name>
            <image>./assets/images/coffee.jpg</image>
            <sizes>
                <size>
                    <name>Small</name>
                    <price>$3.50</price>
                </size>
                <size>
                    <name>Regular</name>
                    <price>$4.00</price>
                </size>
                <size>
                    <name>Large</name>
                    <price>$4.50</price>
                </size>
            </sizes>
            <description>For coffee, please inform the staff of the coffee type.</description>
        </beverage>
    </beverages>
    <otherBeverages>
        <beverage>
            <name>Iced Tea</name>
            <image>./assets/images/icedtea.jpg</image>
            <price>$4.00</price>
        </beverage>
        <beverage>
            <name>Fresh Juice</name>
            <image>./assets/images/juice.jpg</image>
            <price>$6.00</price>
        </beverage>
        <beverage>
            <name>Bottled Water</name>
            <image>./assets/images/water.jpg</image>
            <price>$2.00</price>
        </beverage>
        <beverage>
            <name>Tea</name>
            <image>./assets/images/tea.jpg</image>
            <price>$2.50</price>
        </beverage>
        <beverage>
            <name>Milk</name>
            <image>./assets/images/milk.jpg</image>
            <price>$1.50</price>
        </beverage>
        <beverage>
            <name>Soda</name>
            <image>./assets/images/soda.jpg</image>
            <price>$2.00</price>
        </beverage>
    </otherBeverages>
</menu>
